# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_rototalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselplugin',
            name='variable_width',
            field=models.BooleanField(default=True, help_text='Variable width slides.', verbose_name='variable width'),
        ),
    ]
