# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_rototalc', '0005_auto_20171109_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselplugin',
            name='slide_margin',
            field=models.CharField(default='.5rem', help_text='CSS size for the margin between slides.', max_length=10, verbose_name='slide margin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carouselplugin',
            name='height',
            field=models.CharField(help_text='CSS size for the carousel height.', max_length=10, verbose_name='height'),
        ),
    ]
